- name: checking the datatype
  hosts: localhost
  vars:
    name: upendra
    skills:
      - Devops
      - shell
      - ansible
    experience:
      Devops: 4
      aws: 4
    trainer: true

  tasks:
    - name: print key value pair
      ansible.builtin.debug:
        msg: "name is: {{ name }}"

    - name: print list
      ansible.builtin.debug:
        msg: "skill is: {{ skills }}"

    - name: print map
      ansible.builtin.debug:
        msg: "experience is: {{ experience }}"
    
