- name: loops
  hosts: localhost
  tasks:
    - name: print packages
      ansible.builtin.package:
        name: "hello is: {{ item }}"
        state: present
      loop:
        - git 
        - mysql