- name: loops
  hosts: localhost
  become: yes
  tasks:
    - name: install or unstall
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop:
        - {name: git, state: 'present'}
        - {name: mysql, state: 'absent'}